version: '3.4'
services:
  db:
    build:     
      context: ./postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - app
    expose:
      - "5432"
    container_name: db
  web:
    build:     
      context: ./
    ports:
      - "3001:3000"
    environment:
      POSTGRES_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - app
networks:
  app:
    driver: bridge
